### ISSUE TITLE
Resp not working

### ISSUE THREAD

**Issue by telltouday** [xeonfusion/VSCaptureWave#1]
Hi,
Thank you for the project and source code.
I was trying to read the vitals from geB450 and I can read all the vitals into CSV except respiratory rate
Could you please advise
Thanks

**Comment by xeonfusion** [comment]
Hi,
Respiratory rate (RR) is supported and can be obtained in VSCapture through different mappings in Class2.cs (go through that file, search for rr), depending on the monitor capabilities.

**Comment by telltouday** [comment]
Hi,
I searched in class2.cs and I don't find any mapping for RR. As far as monitor capabilities it is displaying RR on the monitor. So i'm not sure what more should I check to make RR working
Any help would be appreciated
Thanks
