### ISSUE TITLE
Handshake 

### ISSUE THREAD

**Issue by Mouminakm** [xeonfusion/VSCaptureWave#3]
Hey guys 
I'm trying to write a similar app using python. 
Can you please tell me how do you initiate the handshake with the GE B650 monitors? 
I got the cables and connections right but I'm not getting any data out. 
Your help is really appreciated.

**Comment by xeonfusion** [comment]
Have you tried going through the source code? The B650 may need two USB serial cables, connected to each other through a null modem cable, then connected to USB port4 on device. https://sourceforge.net/p/vscapture/discussion/general/thread/71b7c290/
